### PR TITLE
Add Discord OAuth

### LINKED ISSUE #1684: Replace Discord ID Manual Entry with "Login With Discord"
**Is your feature request related to a problem? Please describe.**
At our VA, it appears that, even though there's a link to understand where to get your account ID, users still enter their username or even their email into where a numeric id is supposed to go.

**Describe the solution you'd like**
Implement the Discord OAuth to yank the required information, instead of relying on the user to manually enter these details.

**Describe alternatives you've considered**
Editing the input validation to only take a numeric integer, with the error hint letting the user know they need to read the docs on how to get their ID.

**Additional context**
https://www.youtube.com/watch?v=w5ZLlnid8g0
https://github.com/mbouldo/login-with-discord-php

### PR DESCRIPTION
**Pull request by arthurpar06**
Closes #1684 

We'll have to explain in the docs how to setup this.
You need to create an OAuth application in Discord's Developer Portal (like for RichPresence in VMSAcars, you can use the same app). https://discord.com/developers/applications

Then set these variables in `.env`

```
DISCORD_OAUTH_ENABLED=true
DISCORD_CLIENT_ID={your_client_id}
DISCORD_CLIENT_SECRET={your_client_secret}
```

I couldn't find `private_channel_id` in the Discord docs so I don't know what this field is in the users table and how to fill it. In addition the OAuth connection that I establish has an expiration time but since we don't want to connect the user but just retrieve their id I do not store the tokens to reconnect because we need to send a single request to discord. If we want to make requests to Discord at other places in the code, we must take these tokens into account.

> Having the user's access token allows your application to make certain requests to the API on their behalf, restricted to whatever scopes were requested.

The access token / refresh token actually allow you to interact completely with the Discord API. For example, we can make the user join a server and automatically give him a specific role/nickname. So it could be useful to store them but I didn't really want to change the structure of the table not knowing what you want to do with the discord integration in the future.

This OAuth is based on `laravel/socialite` which allows us to easily addother providers to do OAuth with others webapps if necessary.

### CODE REVIEW

**Comment by arthurpar06** [comment]
Okay so I figured out how to get the `private_channel_id`. This requires putting the `DISCORD_BOT_TOKEN` in `.env` and therefore creating a discord bot (example here https://discordgsm.com/guide/how-to-get-a-discord-bot-token) . Then with this private channel id we can send PMs to a discord user via the bot. Just send a POST request to `https://discord.com/api/channels/{private_channel_id}/messages` with the header `Authorization: Bot {DISCORD_BOT_TOKEN}` and the json `{"content": "Your message"}`. I have to look at how everything works in notifications but I can try to make another PR adding this system to notifications

**Comment by nabeelio** [comment]
This looks awesome. Don't think we need to change notifications right now, though.
Is there more configuration for socialite?

**Comment by arthurpar06** [comment]
For socialite everything works out of the box you just have to add the drivers you want to use. There I put discord for that but if we want we can also add things like login with google etc... There are more than 200 providers that we can add. It also works with IVAO/VATSIM providers but I feel like the procedure for obtaining keys isn't as simple as for discord/others big companies.

So you wouldn't have added notifications with discord DMs? Because I was thinking about that and it would be a lot of work but I was imagining something with user preferences, each user chooses which notifications they want to receive and via which driver (email/discord/others if we add them) and I thought it was cool, maybe a bit overkill but cool/GPDR friendly also.

Since I don't store tokens we can't really talk (100% I mean) with the discord api for a user in fact we talk by acting as the bot whose token we have (to send dm for example) but if we want to do things like, as I said, join servers etc. to really act as the user, we must store the user's tokens. If we don't plan to implement it one day, it's okay not to, but I don't know if we can do a migration later without requiring the account to be unlinked/linked.

**Comment by FatihKoz** [comment]
So how the oAuth application should be configured to work with v7 ? There are options, which should be selected, how stuff should be defined.

If this is being published in a dev release, we should provide the docs about it, otherwise there will be lots of questions about this new feature being shipped :)

**Comment by nabeelio** [comment]
Yes, docs will need to be written, this is mainly testing right now and I think @arthurpar06 is figuring out the "Login with Discord" bit.

**Pull request merged**
