### PR TITLE
Laravel 9 Update

### PR DESCRIPTION
**Pull request by nabeelio**
**Upgrade Guide**

- **WITH THIS UPDATE, PHPVMS NOW REQUIRES PHP 8.0+**
- Please read through the [Laravel Upgrade Guide](https://laravel.com/docs/9.x/upgrade#upgrade-9.0) - there are some settings that are moved/deprecated, and they may apply to you, if you have customized those settings
- The SMTP stream options like `verify_peer` have moved to the root of the SMTP settings. See the [Laravel upgrade guide](https://laravel.com/docs/9.x/upgrade#symfony-mailer)
- Any modules/themes will need to be updated for casting fuel and other types properly (see notes below)

**Notes**

- laravel-gamp (google analytics) removed a) library version incompatible b) wanting to remove google analytics from being included because of gdpr, etc
- Fuel/distance are being properly casted now the `Fuel` and `Distance` styles, so usages of those need to be updated, so something like `$pirep->fuel_used->internal([rounding])` to get the value. There are several methods: `internal()` gets the unit in its internal storage format, `local()` to the unit that the user has selected to view them as, in the admin panel. Both methods take an optional rounding value

**Template Changes**

- [resources/views/layouts/default/app.blade.php](https://github.com/nabeelio/phpvms/pull/1413/files#diff-b18f8ab9ad9ac59f6e444c84a4535f1d17317cb603f0520dfe5c454ef5dcbb5c)
- [resources/views/layouts/default/downloads/table.blade.php](https://github.com/nabeelio/phpvms/pull/1413/commits/4542dcd91b1a23c9880e27e266bac23a903cd047#diff-4392bf4a79e5bb7d69f0785ad60c58588f8ce89c3b3f61455421213b00734180)

**Task List**

- [x] Rewrite the API status caller (reports version, which was removed)
- [x] Refactor factories so they're using the new style
- [x] Models use new [accessor formats](https://laravel.com/docs/9.x/eloquent-mutators#defining-an-accessor)
- [x] Replace recaptcha with hcaptcha
- [x] [Move to Symfony Mailer](https://laravel.com/docs/9.x/upgrade#symfony-mailer)
- [x] Update GH actions to use PHP8
- [x] #1412

### CODE REVIEW

**Comment by FatihKoz** [comment]
*Local Rounding Problems*

`$pirep->fuel_used->local(0)` gives `2763.7882055707` in return (kg)
`$pirep->distance->local(0)` also fails and gives `583.78` in return (km)

`$pirep->fuel_used->internal(0)` works fine 6093 (lbs)

**Comment by FatihKoz** [comment]
*Profile Edit Error, Fresh Install, No Avatar*

Editing profile causes below exception, probably related to user avatar image 'cause it is the only file related part of a user's profile.

`League\Flysystem\Filesystem::delete(): Argument #1 ($location) must be of type string, null given`

**Screenshots**
profile_edit

**Comment by FatihKoz** [comment]
Will send this soon as a pr

image

**Comment by FatihKoz** [comment]
Sent #1435 for this branch

**Comment by FatihKoz** [comment]
Found the reason of why news mails are not working.

image

They are working actually, but not being sent to admin :(

I think we should set both to true for the first user created during setup.

**Comment by FatihKoz** [comment]
PR #1436 is for this branch, and enables html formatting for news mails.

image

**Comment by nabeelio** [comment]
Got it, thanks - added 2 notes for myself to do tomorrow

**Comment by FatihKoz** [comment]
Can we use the latest version of CK Editor too with Laravel9, as we are enabling its use widely I think we should follow the updates.

image

We had several auto opened pr's for it, the last one is #1355

**Comment by nabeelio** [comment]
> Can we use the latest version of CK Editor too with Laravel9 ? As we are enabling its use widely I think we should follow the updates.
> We had several auto opened pr's for it, the last one is #1355

Going to do this as separate PRs to update the js side of things

**Comment by FatihKoz** [comment]
Fresh install with php8.1.3 is **not** possible, below exception occurs.

image

```
[2022-03-09 17:35:35] dev.INFO: Redirecting to database setup  
[2022-03-09 17:35:35] production.ERROR: Attribute value must be of type bool for selected attribute, string given {"exception":"[object] (TypeError(code: 0): Attribute value must be of type bool for selected attribute, string given at D:\\Projects\\v7\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php:70)
[stacktrace]
#0 D:\\Projects\\v7\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php(70): PDO->__construct('mysql:host=127....', 'root', '', Array)
#1 D:\\Projects\\v7\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=127....', 'root', '', Array)
#2 D:\\Projects\\v7\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=127....', Array, Array)
```

**Comment by FatihKoz** [comment]
Fresh install with **php8.0.16** works fine.

**Comment by FatihKoz** [comment]
Testing the branch on my live site, with flights and daily ops.

This error shows up every 5 mins on my laravel log.

```
[2022-03-13 17:20:02] prod.ERROR: Class "PDO" not found {"exception":"[object] (Error(code: 0): Class \"PDO\" not found at /vendor/laravel/framework/src/Illuminate/Database/Connection.php:1470)
```

[PDO Error.txt](https://github.com/nabeelio/phpvms/files/8240269/PDO.Error.txt)

Trying to figure out what it can be, cron or a module or something else ? Not much clues in the error and stack trace below.

**Comment by FatihKoz** [comment]
And this is the last entry from my cron log, this makes me think that above PDO error is somehow related with cron.

```
[2022-03-13 13:20:02] prod.ERROR: Command "version" is not defined.

Did you mean one of these?
    phpvms:version
    session:table {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"version\" is not defined.

Did you mean one of these?
    phpvms:version
    session:table at /vendor/symfony/console/Application.php:683)
[stacktrace]
#0 /vendor/symfony/console/Application.php(259): Symfony\\Component\\Console\\Application->find()
#1 /vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#2 /vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#3 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#4 /bin/cron(25): Illuminate\\Foundation\\Console\\Kernel->handle()
#5 {main}
```

**Comment by FatihKoz** [comment]
I think the cron error is related to this 'cause it is the only piece of code, running a version command every time cron runs

https://github.com/nabeelio/phpvms/blob/Laravel9/bin/cron#L21-L26

**Comment by nabeelio** [comment]
PDO is a PHP class from the PDO driver, maybe something not configured right with the command line PHP? That command throwing an error is strange though, I'll look

**Comment by FatihKoz** [comment]
This is what I got at cpanel for php8.1

image

Looks like I have every extension we need there and enabled.

**Comment by FatihKoz** [comment]
`[2022-03-13 18:00:06] prod.INFO: Hourly: Removing expired Simbrief entries`

Cron started working again, that suggestion provided with the error worked :) And no repeating errors in laravel log on every cron run.

**Comment by FatihKoz** [comment]
Also saw this with Discord Notifications

image

Notice the difference in distance, either it is not sending `0 km` or we have an unnecessary `/` there. Before (with latest dev build) notification was like below

image

**Pull request merged**
