### PR TITLE
Fixt DEV Seeder

### PR DESCRIPTION
**Pull request by mfehr94**

### CODE REVIEW

**Comment by nabeelio** [comment]
Why are you changing this? I'm leaving the UUID field IDs as strings, and probably am going to offset all the other ones. They're hard to differentiate in the UI and when examining tables.

**Comment by mfehr94** [comment]
Because of this error: 


Aber eigentlich muss nur die flight_id im subfleet_flight Schema von int zu string geändert werden

**Comment by nabeelio** [comment]
That's more of a schema issues, I fixed the error here 81667a0
Thanks!

**Comment by nabeelio** [comment]
BTW, what command did you run?

**Comment by mfehr94** [comment]
php artisan migrate:refresh --seed

**Comment by nabeelio** [comment]
Thanks. I've fixed the underlying issue, let me know how you're making out now.

**Comment by mfehr94** [comment]
Works fine

**Pull request closed without merging**
