### PR TITLE
Improve Admin blades

### PR DESCRIPTION
**Pull request by FatihKoz**
Added user_id and made user model optional, so the page will not fail if it hits a hard deleted user's pirep

Also improved the visual style of the buttons, made them look better with separation etc.

pirep_card

### CODE REVIEW

**Comment by FatihKoz** [comment]
Flight Search result

flights

**Comment by FatihKoz** [comment]
> Why'd you close this one, I didn't see it before

I deleted all my forks with and without open pull requests. Like configmaps, doc changes and core v7 ‘cause people are downloading them from my repo/fork and then compaining that it is not working etc (due to missing vendors for v7 as expected)

I can re-send those admin blade improvements though, i still have that files at my live server and personal repository but doc changes I did waiting approval are gone I assume.

**Comment by nabeelio** [comment]
Yeah you can resend this one

**Comment by nabeelio** [comment]
I'm very behind on PRs

**Comment by FatihKoz** [comment]
This was the last open user PR for v7 ;) Rest is mostly related with auto fixes of vendors and old wontfix tagged ones.

Docs had some changes/corrections though :)

**Pull request closed without merging**
