### PR TITLE
Fix Ranks Seeder

### LINKED ISSUE #1351: Ranks Seeder runs on every module install (Bug Report)
```
[2021-11-14 19:55:40] production.INFO: Running seeder  
[2021-11-14 19:55:40] production.INFO: Seeding .D:\Projects\phpvms/app/Database\seeds/prod/ranks.yml 
```
Seeder runs on every module install and seeds `ranks.yml`. This happens for modules without seeds or migrations too.

**Version**
Latest dev as of date

**To Reproduce**
1. Do a fresh install
2. Edit your ranks, specially edit "New Pilot"
3. Install a module
4. Check logs and your ranks
5. New Pilot will be defaulted and the seeding entry will be in the log

**Expected behavior**
If not mandatory for some reason it should not run, or at best it should check if there is a "New Pilot" entry before overwriting it.

### PR DESCRIPTION
**Pull request by arthurpar06**
Close #1351

### CODE REVIEW

**Comment by nabeelio** [comment]
In the ranks migration (2017_06_21_create_ranks_table), add:

```php
        DB::table('ranks')->insert([
            'id' => 1,
            'name' => 'New Pilot',
            'hours' => 0,
            'acars_base_pay_rate' => 50,
            'manual_base_pay_rate' => 25, 
        ]);
```

**Comment by arthurpar06** [comment]
hm creating the rank in the migration in test/dev is not great, that's probably why it was seeded in prod...

**Comment by nabeelio** [comment]
In the dev/ranks.yml, remove the id: 1 entry, since that'll be in the migration now

**Comment by arthurpar06** [comment]
I can do it but I think it won't solve everything. The crashing test tries to create ranks with id 1 and 2, that's what crashes.
https://github.com/nabeelio/phpvms/blob/dev/tests/ImporterTest.php#L721

**Comment by nabeelio** [comment]
Yeah, try removing those IDs

**Comment by arthurpar06** [comment]
I can't do that, there are in the `subfleet.csv` ranks which are referenced by their id for the import. So the relationships between `rank <> subfleet `tests are based on that and afterward the tests do not pass

**Comment by arthurpar06** [comment]
Instead of putting this insertion in the migration we can put it in a step of the importer... It's not very clean but it'll work for sure

**Comment by nabeelio** [comment]
I'm making a change to the seeder to add a new parameter. The importer wipes all the data anyway

**Comment by nabeelio** [comment]
Though I guess the tests can use an id like 99 or 100 instead of starting from 1

**Comment by arthurpar06** [comment]
yes they can that's for sure

**Comment by arthurpar06** [comment]
I think I got them work by changing the IDs. Give me time to run them all but it should be good

**Comment by arthurpar06** [comment]
yes they all pass, if you want I push that and we're good without changing seeder logic

**Comment by nabeelio** [comment]
I have a separate PR for that

**Comment by nabeelio** [comment]
Yeah please push that, thanks!!

**Pull request merged**
