### PR TITLE
Clean up logs

### PR DESCRIPTION
**Pull request by arthurpar06**
This significantly lightens the logs, which were filled with unnecessary data. For example, displaying `$request->post()` every time filled the logs with all the information the server received with each update of a PIREP and its submission. When a PIREP is submitted, we receive the OFP, etc., so the entire OFP was being logged, leading to very heavy log files.

There are also some listeners in the VACentral module that do nothing more than send huge lines of code to the logs with each PIREP update/submission. Do you know where I can find the source code of this module to create a PR and remove that?

This is still ongoing, I've deployed it on my production server to lighten the logs, and I'm waiting to see if there  are still things being logged unnecessarily. I didn't want to remove too much information, so I left a log when we receive a PIREP update, but I think this can be discussed because I'm not sure it's necessary.

### CODE REVIEW

**Comment by FatihKoz** [comment]
Thanks man, this look like much more effective for tracking back stuff... As we do not need the full request on each update, specially that simbrief plans (with full notams) is useless... We know it works, so no need to debug it anymore :)

For VA_Central module, I have no clue sorry... I check Nabeel's project page but it is not there either, it may be a private repository. Maybe you can work on a local copy and send in the files changed directly to him.

I will start testing today, once I update to latest dev, will add the log changes manually to see how it goes ;)

**Comment by FatihKoz** [comment]
Any idea, where this can come from? I changed the files on my live servers to test logs, cleaned cache, but this keeps being recorded and with full request including simbrief ofp 😞 

```
[2024-01-24 08:54:47] production.DEBUG: PIREP Update, pirep_id: G9awkxgpqzb9DaoL, user_id: 70  
[2024-01-24 08:54:47] production.INFO: Received acars update event [{"App\\Events\\AcarsUpdate":{"pirep":{"id":"G9awkxgpqzb9DaoL","user_id":70,"airline_id":1,"aircraft_id":38,"event_id":null,
```

**Comment by arthurpar06** [comment]
Those are the logs I was referring to, those in VACentral. There are two listeners in VACentral that do nothing but add these logs, and I don't know how to remove them since I can't find the VACentral module repo...

**Comment by FatihKoz** [comment]
Sometimes what you search for sits in front of your eyes 😉 

image

We can null them out in this pr...

**Comment by arthurpar06** [comment]
Indeed...
Thank you ;)

**Comment by FatihKoz** [comment]
I am not sure about deleting those files, as they may be a part of Nabeel's future ideas (like making VaCentral a common place where all v7 va's talk each other digitally etc.)... 

So I would suggest only dashing out the log lines (yes they are the only lines in those listeners but, at least they will be there) 😉

**Comment by arthurpar06** [comment]
Yeah, I see what you mean.
I'll wait to hear Nabeel's opinion. If he wants me to put them back, I will, but I thought having 2 fewer listeners to call each time would be more optimized than calling an empty listener.

**Pull request merged**
