### PR TITLE
Add Laravel Backup

### PR DESCRIPTION
**Pull request by arthurpar06**
This PR adds `spatie/laravel-backup` which will allow admins to backup their database. Here are some important setting that can be set in the .env:

-`BACKUP_ENABLED`: true/false (default)
-`BACKUP_DISKS`: comma-separated, local by default. Create disks in `config/filesystems.php`.
-`BACKUP_ARCHIVE_PASSWORD`: AES256 encryption password if set. empty/null = disabled (default)
-`BACKUP_FAILED_NOTIFICATIONS_CHANNELS`: `mail` (default), `discord`, `mail,discord`, or empty.
-`BACKUP_SUCCEED_NOTIFICATIONS_CHANNELS`: `mail`, `discord`, `mail,discord`, or empty (default)
-`BACKUP_NOTIFICATIONS_MAIL_TO`: Email for notifications.
-`BACKUP_DISCORD_WEBHOOK_URL`: Discord webhook URL.
-`BACKUP_DISCORD_USERNAME`/`BACKUP_DISCORD_AVATAR_URL`: Discord customization.

### CODE REVIEW

**Comment by nabeelio** [comment]
I used to have this in phpvms before but removed it because it was causing issues with storage and slowing things down with the cron on larger backups. Lemme look at your pr in more detail later

**Comment by arthurpar06** [comment]
no worries. The backups are compressed and start around 1am. I have had it in production since the beginning. I can't really talk about the CPU impact because my production is on a good vps. As for the backups size, my db is a little over 2GB and the backups are less than 300MB each. Additionally, enabling this feature is optional, disabled by default.

**Comment by arthurpar06** [comment]
Yeah we can do that. We just need to look at how we want to push to this s3env because I think that depending on how we want to push (ftp, sftp, s3...) we need additional composer packages

**Comment by nabeelio** [comment]
@FatihKoz that's a good idea, I think maybe in another PR we can define a disk which can be entirely setup through the env

**Comment by FatihKoz** [comment]
yeah it would be great, I am just thinking on making things (specially updates and installations) easy :)

**Pull request merged**
