### PR TITLE
News WYSIWYG

### PR DESCRIPTION
**Pull request by russellwwest**
Adds WYSIWIG Editing for news, this also updates the latest news widget to render the formatted news

### CODE REVIEW

**Comment by nabeelio** [comment]
Have you tested the rendering with the email that gets sent out with the news?

**Comment by russellwwest** [comment]
Ahhh, no - let me have a look :)

**Comment by russellwwest** [comment]
I think that is the only place for emails?

**Comment by FatihKoz** [comment]
Are there any plans to show formatted news at acars too ? 'Cause as far as i know, latest news (only the last one) are being read by acars dashboard and any html formatting will be visible there too (as plain text of course)

**Comment by nabeelio** [comment]
Yep I will need to fix on the ACARS side too but have been debating on how

**Comment by nabeelio** [comment]
I'm going to close this for now because I don't have a good solution for this yet on the ACARS side.

**Pull request closed without merging**
