### PR TITLE
Disable toDiscordChannel()

### LINKED ISSUE #1741: Duplicate Discord Notifications and Exceptions
We get exceptions while publishing news with latest dev build `7.0.0-dev+231224.6b9658`

https://github.com/nabeelio/phpvms/blob/6b9658a4e37e193e00e5b1f4b1084130a64aaf1c/app/Notifications/Messages/NewsAdded.php#L51

https://github.com/nabeelio/phpvms/blob/6b9658a4e37e193e00e5b1f4b1084130a64aaf1c/app/Notifications/Messages/NewsAdded.php#L53

```
production.ERROR: Attempt to read property "ident" on null (app/Notifications/Messages/NewsAdded.php:51)
production.ERROR: Attempt to read property "name_private" on null (app/Notifications/Messages/NewsAdded.php:51)
production.ERROR: Call to a member function resolveAvatarUrl() on null (app/Notifications/Messages/NewsAdded.php:53)
```

When those calls are changed with fixed strings or dashed out, we get multiple/duplicate discord notifications (matching the count of users who opted in for non administrative mails)

test result

By the mean time, a proper discord notification gets dispatched from `Broadcasts` (last message in above screenshot)

https://github.com/nabeelio/phpvms/blob/6b9658a4e37e193e00e5b1f4b1084130a64aaf1c/app/Notifications/Messages/Broadcast/NewsAdded.php#L31

So the question is, why do we have the same function in mail channel ?

Should we remove function from `Messages/NewsAdded.php` completely 'cause it is working properly when called from `Messages/Broadcasts/NewsAdded.php` ?

### PR DESCRIPTION
**Pull request by FatihKoz**
Aims to close #1741 

Needs testing and discussion about initial implementation before merge.

### CODE REVIEW

**Comment by arthurpar06** [comment]
I'll test it right away. You also need to remove the `DiscordWebhook::class` from here 

https://github.com/nabeelio/phpvms/blob/6b9658a4e37e193e00e5b1f4b1084130a64aaf1c/app/Notifications/Messages/NewsAdded.php#L32

**Comment by arthurpar06** [comment]
It seems like everything is working. I received the emails, and the Discord notification has been sent. However, it's a bit ugly to have HTML in the Discord notification, but I'm not sure if there's anything we can do about that.

image
image
image

**Comment by FatihKoz** [comment]
yeah, discord needs markdown formatting as far as I remember and html messes it up.

If we can implement something converting html to markdown, they will look better for sure.

**Comment by arthurpar06** [comment]
That's exactly what I was looking for

**Comment by FatihKoz** [comment]
Maybe this ;

https://github.com/thephpleague/html-to-markdown

**Comment by arthurpar06** [comment]
Yeah I also found this, let me give it a try

**Comment by arthurpar06** [comment]
The headings aren't converted very well, but it's already better. At least we have paragraphs and lists.

image

**Comment by FatihKoz** [comment]
Then we are waiting another PR for it to be added and implemented.

To be honest, headings are ok. At least better than nothing. Rest looks ok as you said, much better compared to what we have now.

**Comment by arthurpar06** [comment]
Yeah, we'll create another PR for that. I might also try adding tests for notifications. It's happened several times that we realize a notification isn't working, and adding a few unit tests to ensure they work wouldn't be a bad idea, I think.

**Comment by FatihKoz** [comment]
Ready to merge.

**Pull request merged**
