### PR TITLE
Update Metar Decoding (Text Correction Only)

### PR DESCRIPTION
**Pull request by FatihKoz**
**SKC** means **Sky Clear** or _Clear Skies_. , it is not used as an acronym for No Significant Changes Expected (which is NOSIG)

Rest is ok

### CODE REVIEW

**Comment by nabeelio** [comment]
There is a test failing, can you update file too? If you click "Details" in the "Travis CI - Pull Request" and click one of the runtimes; here's the error:

```
1) Tests\MetarTest::testMetar1
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'A few at 1676 meters; scattered at 2896 meters; broken sky at 3353 meters; broken sky at 7010 meters'
+'Few at 1676 meters; scattered at 2896 meters; broken sky at 3353 meters; broken sky at 7010 meters'
/home/travis/build/nabeelio/phpvms/tests/MetarTest.php:68
```

**Comment by FatihKoz** [comment]
I just delete the -a- from 'A few' and capitalized the first letter like 'Few' , failing to build just for one letter is strange. If you wish I can redo the complete process.

**Comment by nabeelio** [comment]
Yeah just go to here `/home/travis/build/nabeelio/phpvms/tests/MetarTest.php:68` and fix the text. And check if there are any others that are changed

**Comment by nabeelio** [comment]
You can go to "open with" in the top right and either clone this branch to your desktop, or use codespaces

**Comment by FatihKoz** [comment]
Downloaded the desktop app and made the change as a commit. Hope it passes the build test this time

**Comment by nabeelio** [comment]
Thank you!

**Pull request merged**
