### PR TITLE
Fix Flight Importer/Exporter and Aircraft Importer

### LINKED ISSUE #1647: Flight Exporter, Distances get converted to local unit
While exporting flights, internal distance gets converted and exported as local unit.

**Version**
7.0.0-dev+231022.d69a3b

**To Reproduce**
1. Go to settings, change your distance units to miles or kilometers
2. Go to flights, export all or some of your flights
3. Check the file, it will have your local unit exported
4. Import the same file again
5. Those distance values will be considered as internal units (nautical miles)

**Expected behavior**
Import / Export features should always use internal units, or we should have units saved/selected during import

### LINKED ISSUE #1648: Flight Importer, Empty fields are converted to zero or dates during import
While importing flights, empty fields (like route_leg, load_factor, start_date, end_date, event_id) is not recorded as `null` but they are imported either as `0` or with strange dates.

**Version**
7.0.0-dev+231022.d69a3b

**To Reproduce**
1. Prepare a flights.csv with mentioned dates empty
2. Go to admin > flights and click on import
3. After the import, check the admin > flights page or admin > flight edit
4. You will see that you will have dates, load_factor set to 0
5. Export the flights back, check the exported file to see the auto generated values

**Expected behavior**
Empty fields should be kept as they are and recorded as `null`

### LINKED ISSUE #1650: Aircraft Importer, Empty FIN field causes problems
While importing aircraft, empty `fin` field causes sql integrity constraint violation error.

**Version**
7.0.0-dev+231022.d69a3b

**To Reproduce**
1. Export some of your aircraft (not subfleet)
2. Check the `fin` fields in the csv, they should be empty
3. Import the file back

**Expected behavior**
Empty fields should not cause `unique` checks to fail and model should not return empty strings, they should return `null`

**Additional context**
Example aircraft.csv
```
subfleet,iata,icao,hub_id,airport_id,name,registration,fin,hex_code,mtow,zfw,status
A20N-AJET,20N,A20N,,LTFJ,TC-LUK,TC-LUK,,,79000,,A
A20N-AJET,20N,A20N,,LTFJ,TC-LUL,TC-LUL,,,79000,,A
A20N-AJET,20N,A20N,,LTCG,TC-LUN,TC-LUN,,,79000,,A
A20N-AJET,20N,A20N,LTAC,LTBJ,TC-LUO,TC-LUO,,,79000,,A
A20N-AJET,20N,A20N,LTAC,LTAC,TC-LUV,TC-LUV,,,79000,,A
A20N-AJET,20N,A20N,LTAC,LTAC,TC-LUY,TC-LUY,,,79000,,A
A20N-AJET,20N,A20N,LTAC,LTAC,TC-LUZ,TC-LUZ,,,79000,,A
```

Import result
```
Error in row 3: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'aircraft_fin_unique' (Connection: mysql, SQL: update `aircraft` set `hub_id` = , `fin` = , `hex_code` = 4df98ce6, `zfw` = , `aircraft`.`updated_at` = 2023-10-23 17:38:55 where `id` = 827)
Error in row 4: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'aircraft_fin_unique' (Connection: mysql, SQL: update `aircraft` set `hub_id` = , `fin` = , `hex_code` = 4cb04e1e, `zfw` = , `aircraft`.`updated_at` = 2023-10-23 17:38:55 where `id` = 828)
```

### LINKED ISSUE #1660: Flight  Import - Not Calculating Distance When Field is Left Empty
**Describe the bug**
When importing flights, the flight distance is not calculated when the distance field is left blank/empty in the import CSV file.

**Version**
version 7.0.0-beta.5

**To Reproduce**
1. Go to the admin > operations > flights page,
2. Click on Import from CSV.
3. Select file to import (that contains empty distance field).
4. Click Start Import button.
5. Once import is successful, go back to the flights page and select once of the imported flights.
6. The distance will be blank.

**Expected behavior**
After the import, the distance should be calculated for the imported flights.

**Screenshots**
Distance field on the imported flight:
image

**Additional context**
Attached file used for import test:
[flights-test-import.csv](https://github.com/nabeelio/phpvms/files/13197075/flights-test-import.csv)

### LINKED ISSUE #1661: Flight Import | firstOrNew Fails
During flight import, `**firstOrNew**` fails to match existing flights and always creates a new model instance, which results in duplicate flights if same file is imported again.

**Version**
7.0.0-dev+231027.67ef30

**To Reproduce**
1. Go to admin > flights > import from csv
2. Import a file with some new flights
3. Go back to admin > flights > import from csv again
4. Import the same file
5. Check your flights, you will see the duplicated flights

**Expected behavior**
We should update matching records, not re-create new flights on every import

**Screenshots**
duplicate flights

[test.csv](https://github.com/nabeelio/phpvms/files/13198582/test.csv)

### PR DESCRIPTION
**Pull request by FatihKoz**
Closes #1648 
Closes #1647 
Closes #1650 
Closes #1660 (Only the main issue, distance calculation)
Closes #1661 

* Export internal distance unit (Flight)
* Check for blank row values, return their attributes as `null` (Flight)
* Check for blank `distance` and calculate if necessary (Flight)
* Check for blank `fin` field and return as null instead of empty string (Aircraft)

### CODE REVIEW

**Comment by FatihKoz** [comment]
Closes #1650 

* Check for blank `fin` row and return as `null` instead of empty string

**Comment by nabeelio** [comment]
Why `null` vs empty?

**Comment by nabeelio** [comment]
Nevermind, that's weird on the blank, hmm

**Comment by FatihKoz** [comment]
Simple, if you leave them as empty strings somehow it causes problems... Details are being discussed at discord and this was the only solution I found.

**Comment by FatihKoz** [comment]
Fixed `distance` calculation logic and position as it should run before the `$flight->save()` call.

**Comment by FatihKoz** [comment]
Hope `firstOrNew()` issue is solved too, as it looked like related with **SoftDeletes** and not getting a proper match.

Checking;

* Flight Number
* Route Code
* Rote Leg
* Departure Airport
* Arrival Airport

to get a perfect match to update, and if a match found in soft deleted fields it gets restored (by nulling `deleted_at` field)... Otherwise a new Flight instance is created.

**Review by nabeelio — APPROVED** [review]

**Pull request merged**
