### PR TITLE
Refactoring for Simbrief not working #1005

### LINKED ISSUE #1005: Simbrief ACARS not working properly
Gives an stacktrace of API route missing parameters

```
[2021-01-24 22:59:18] dev.ERROR: Missing required parameters for [Route: api.flights.briefing] 
[URI: api/flights/{id}/briefing]. {"userId":1,"exception":"[object] (Illuminate\\Routing\\Exceptions\\UrlGenerationException(code: 0): Missing required parameters for [Route: api.flights.briefing]
[URI: api/flights/{id}/briefing]. at /var/www/demo.phpvms/vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php:17)
```

### PR DESCRIPTION
**Pull request by nabeelio**
Fix a couple of issues - 

1. The simbrief ID should only "transfer" over to the PIREP once the PIREP is filed... that prevents a cancellation/etc after a profile from discarding the briefing (in case it's used over).
2. The `SimBrief` HTTP resource uses the `flight_id` param with a lookup of the `user_id` + `flight_id` - but if that `flight_id` association is removed (like it is on prefile), then the URL generated as the response (on where to look up the briefing) is then errored out, with a blank being passed. Change the URL so that the briefing ID is passed, and then do a check on the user to make sure its their own briefing that they're using (a requirement from Simbrief)

Closes #1005

@FatihKoz Can you pull this branch down and test?

### CODE REVIEW

**Comment by FatihKoz** [comment]
Will pull and test, earliest it will be 8 hours later though 'cause it is almost 3 am here. Will report back after testing.

**Comment by nabeelio** [comment]
Take your time, thanks

**Comment by FatihKoz** [comment]
Just tested ... 

phpvms7 : Generated a simbrief pack for a flight
acars : search flights , select the flight with simbrief pack , load , click start flight

No Errors.

Should I fly and finish the flight to test if it goes well till end ? ( with a short visual pattern maybe )

**Comment by nabeelio** [comment]
Yes, that'd be great, this should also fix the brief being attached to the pirep at the end of the flight

**Comment by FatihKoz** [comment]
Well , tried to finish the flight with a short and low pattern at departure airport ... Probably because the latest checks for takeoff to enroute phase change acars did not allowed me to finish the flight after landing , thus cancelled the flight.

Now doing another pattern but will climb higher to trigger the enroute phase and will land back to origin

**Comment by nabeelio** [comment]
I can reduce that to 100 feet in the next build

**Comment by FatihKoz** [comment]
Second test flight ... Created a simbrief pack for the flight 

Acars -> search -> load -> start flight ... No errors
Take off -> climb to trigger enroute phase -> return back and land to origin -> end flight ... No errors

Check database / simbrief table -> flight_id was null , pirep_id was populated
Check phpvms -> Simbrief was attached to the pirep as expected
Check phpvms -> **Move self to origin again 'cause my diversion was not recognized** -> Go to flights -> try to create simbrief -> No old briefings displayed as expected

Except the part that diversions are not recognized yet by acars, all went fine.

**Comment by nabeelio** [comment]
Diversions are a separate issue but the rest is working so that's great, thanks!

**Comment by FatihKoz** [comment]
> Diversions are a separate issue but the rest is working so that's great, thanks!

Sure , thanks for the quick fix

**Pull request merged**
