### PR TITLE
add download thumbnail

### PR DESCRIPTION
**Pull request by arthurpar06**
It may be necessary to review the thumbnail position/style in the frontend and the way to make the distinction between the thumbnail and the file when we upload them.

### CODE REVIEW

**Comment by nabeelio** [comment]
@arthurpar06 is this working as you expect?

**Comment by arthurpar06** [comment]
@nabeelio for the upload and the backup everything works fine, after as I said it may be necessary to review the frontend part (image size and position) and add a label or something like that to differentiate the two `<input type="file" />` in the admin

**Comment by nabeelio** [comment]
@arthurpar06 is this still active?

**Comment by arthurpar06** [comment]
No, you can close it

**Comment by nabeelio** [comment]
Is it mostly working, though?

**Comment by arthurpar06** [comment]
Yes I think we just had to revise the frontend a bit

**Comment by nabeelio** [comment]
@FatihKoz would you be able to pull this PR down and see what fix/changes it might need on the frontend?

**Comment by FatihKoz** [comment]
Why not, but earliest possible time is Saturday or Sunday for a nice
check/update.

23 Ağu 2022 Sal 19:08 tarihinde Nabeel S. ***@***.***> şunu
yazdı:

**Comment by nabeelio** [comment]
@FatihKoz no rush at all

**Comment by FatihKoz** [comment]
Just a question, do I need to pull down and create a new pr with my changes (which also will include fixes to current one, stlye fix and removal of down migration) ? Or should I only work on default theme frontend changes when able ?

I think I will not be able to commit on this PR 'cause I am not the owner and/or moderator etc.

**Comment by FatihKoz** [comment]
image

**Comment by FatihKoz** [comment]
I think we need more than just frontend/blade changes on this @nabeelio , there are some issues;

* If there is no file uploaded along with thumbnail , it does not get uploaded (imagine a scenario like below)

image

  path field: `https://flightops.turksim.org/test.zip`
  thumbnail field: `C:\Users\fatih\AppData\Local\Temp\phpD1E4.tmp`

* Model does not return full url for the thumbnail , it just returns what is recorded to database as expected
  `files/thumbnails/B8p07y7DdJP8Zbyl_startbootstrap-small-business-gh-pages_thumbnail.jpg`

Second one is easy, it can be fixed with a model update to generate a new attribute like `imageurl` or it can be handled in blade with url helpers. First one needs some work.

Results from a quick look and test :(

**Comment by nabeelio** [comment]
@arthurpar06 do you want to fix this up or should I close it

**Comment by arthurpar06** [comment]
I can try to take a look when I have some free time but I think we can close, it's not a revolutionary feature either

**Pull request closed without merging**
