### PR TITLE
Make Free Flights Optional

### LINKED ISSUE #1255: Make Free Flights Optional (Feature Request)
**Is your feature request related to a problem? Please describe.**
No, this is a new feature request.

**Describe the solution you'd like**
Admins should be able to allow or block "free flight"s easily according to their operational needs.

(Free Flight = Flights started by entering all details to vmsAcars new flight form and reporting)

**Details / Alternatives**
We are checking almost everything during pre-filing phase (like aircraft suitability etc) at phpvms side so this could be checked there too. Just do a basic check with Airline / Flight Number / Departure Airport / Arrival Airport, if a result is returned from phpvms flight repository then allow flight, if nothing found throw an exception and do not pre-file the pirep.

Due to flexibility, this should be tied to a setting at phpvms admin side.

Alternative solution may be controlling this at acars side.

Another alternative may be leaving this as it is now and let airline admins to build up their own solutions for this matter.

### PR DESCRIPTION
**Pull request by FatihKoz**
PR adds a new setting and a check at pirep prefile level, to allow/refuse "Free Flight"s.

**By default, the setting is disabled** (unchecked), so "Free Flight"s are allowed. Admins will be able to enable/disable according to their operational needs.

Closes #1255

### CODE REVIEW

**Comment by FatihKoz** [comment]
Forgot to add the result, when the setting is enabled and pilot tries to enter details to new flight form manually, here check fails 'cause va does not have that flight available.

flight_check_1

**Comment by FatihKoz** [comment]
@nabeelio , if you are not interested in this I will close and delete... I am waiting at least for a comment for more than 2 months :)

**Comment by nabeelio** [comment]
Sorry - I've left it open so I can look at it in more detail but I haven't gotten the chance. I'm still working on this on the ACARS side so I'm not sure which changes I'll need on the phpvms side yet.

**Comment by FatihKoz** [comment]
Understood, I am using this on my live server and had no problems so far. Only downside is, pilot enters every little detail and gets the message after clicking start flight. (if the details they entered does not match of course)

A direct acars side change may be more effective (like making the fields read only and not allowing them to enter at all)

**Comment by FatihKoz** [comment]
Closing this and deleting the branch, latest alpha release works fine ;) 

I think phpvms would not need any changes for disabling free flights, acars update will be more than enough as it seems.

**Pull request closed without merging**
