### PR TITLE
Refactored AcarsTest.php

### PR DESCRIPTION
**Pull request by bryanlopezinc**
Refactor AcarsTest class

### CODE REVIEW

**Comment by nabeelio** [comment]
I'm not sure why I understand the motivation behind refactoring? A lot of this was split up the way it is, albeit more verbose, to make debugging and placing breakpoints, and viewing values for TDD much easier.

**Comment by bryanlopezinc** [comment]
I just taught it was a little harder to read as methods were a bit long with a lot of variables. I think debbuging and viewing values is still very much achievable.

**Comment by nabeelio** [comment]
If you can fix the style ci checks, I'll take a closer look when I'm on the computer

**Comment by nabeelio** [comment]
I'd apply the diff that styleci is giving you, that should fix it

**Pull request closed without merging**
