### PR TITLE
Fixes to Csv import Exports 

### PR DESCRIPTION
**Pull request by lesmar54**
Part of the fixing of csv files for import and export

### CODE REVIEW

**Comment by lesmar54** [comment]
Merged all of the fixes into one patch now

**Comment by FatihKoz** [comment]
style

If you fix the style error, I think they will pass the build tests

**Review by lesmar54 — COMMENTED** [review]
corrected spacing for public static and spaces after callsign column

**Comment by lesmar54** [comment]
Done the changes to align the public static and remove two spaces after callsign  ’nullable’,

**Comment by FatihKoz** [comment]
You still have styling errors.

**Comment by lesmar54** [comment]
> You still have styling errors.

I went to the edit file and aligned PUBLIC but do not understand where the style issue is now

**Comment by lesmar54** [comment]
Passed the styling at last I think

**Comment by FatihKoz** [comment]
Yes, now the owner of the main repository ( phpvms / nabeel ) can allow other checks to be executed for this.

This needs manual input at the moment but when you reach to a level all will be automatically done and then the owner will just check and decide what to do (if your changes pass all checks of course).

Now you can safely close all those other "single file" pull requests, they are not needed anymore 'cause all is here ;)

**Comment by nabeelio** [comment]
Some tests are still failing, I can take a look in a little bit.

**Comment by FatihKoz** [comment]
Yeah, `flights_empty_fields.csv` this one needs to updated too. It is causing the import test to fail.

**Comment by FatihKoz** [comment]
There may be more files to edit though, just checked the tests/data folder. All files regarding aircraft / flights / subfleets needs to edited according to the new field requirements.

**Comment by lesmar54** [comment]
Ok I will look at these other csv files in the morning now I know how to AC filed to a pr

**Comment by nabeelio** [comment]
Yeah just add onto this PR

**Comment by lesmar54** [comment]
3 other csv files added to PR

**Pull request merged**
