### PR TITLE
Update Flight Resource

### LINKED ISSUE #1607: Display Flight Callsign (Flight Resource) | Feature Request
**Is your feature request related to a problem? Please describe.**
No, this is a feature request.

**Describe the solution you'd like**
When an alphanumeric callsign is defined for a flight, this should be visible on acars flight list/search. So a pilot would know the proper ATC callsign of that flight.

To simplify things, we can display both ATC Callsign and Flight Ident (with Code and Leg info) side by side.

**Describe alternatives you've considered**
Not much, we can leave current flight resource as it is.

image

### PR DESCRIPTION
**Pull request by FatihKoz**
Closes #1607 

Adds callsign to flight ident, by checking simbrief callsign option.

When mentioned option is enabled, pilots will be forced to use their idents as callsign, so displaying a flight's callsign will be meaningless and confusing pilots. But when that option is not enabled, pilots should be able to see and use a flight's assigned callsign.

Callsign is either the flight number itself or a special alphanumeric string defined by airline per flight.

### CODE REVIEW

**Comment by nabeelio** [comment]
Wouldn't we want this to be set on the phpvms side, too? If they're not using simbrief? Or it doesn't matter in that case

**Comment by FatihKoz** [comment]
Sorry didn't understand the question Nabeel... This is already defined at phpvms side, we are just letting the pilot know the callsign of the flight at acars side by displaying it on search screen.

At phpvms side, if an airline is either using or not using simbrief, this info can be displayed to the pilot at flight search or details page. If you want to show it there too, I can add the blade changes to this pr too.

**Comment by nabeelio** [comment]
Yea, can you add it to the details/search? Thank you. Do I need to make a change in ACARS?

**Comment by FatihKoz** [comment]
Ok, I will add the callsign to flight show and search results too... Not a big deal.

Well, at acars side I am not sure... If you wish to change the layout, maybe we can just change the title of that field. It now says `Flight Number` but it displays `Flight Callsign` and full flight ident with code and leg.

**Comment by FatihKoz** [comment]
image

image

Callsign display was already in these blades, but it was not model provided. Updated them to use `$flight->atc` and applied the same setting as flight resource.

**Comment by FatihKoz** [comment]
This is the acars result

image

If there is a callsign and if the VA does not force pilot ident usage as callsign, flight callsign is displayed (same as blades)

**Comment by FatihKoz** [comment]
Would you please re-run tests as it fails at MySQL side and I can not re-run them (even though GitHub desktop tries to trigger them)

All should pass without errors, no test critical features/changes present.

**Comment by nabeelio** [comment]
Is that setting already in the settings setting.yml file?

**Comment by FatihKoz** [comment]
> Is that setting already in the seeds setting.yml file?

Of course it is. It is there any used for forcing pilot ident as atc callsign (which overrules any flight callsign / flight number). As explained before some VA's prefer forcing people to use their idents as callsign when online, that setting is for that and useful for this pr too.

**Pull request merged**
