### PR TITLE
Add morphable properties to Flight model

### PR DESCRIPTION
**Pull request by nabeelio**
#1681

### CODE REVIEW

**Comment by BossOfGames** [comment]
For a polymorphic relationship, doesn't the column name containing the type need to end with `_type` for it to not throw a fit?

**Comment by nabeelio** [comment]
By convention, but good call. I just realized the `morphTo` isn't setup properly

**Comment by BossOfGames** [comment]
Should we have test coverage on this?

**Comment by nabeelio** [comment]
Don't think it needs it, it's leveraging a Laravel feature and adding some columns.

**Comment by BossOfGames** [comment]
> Don't think it needs it, it's leveraging a Laravel feature and adding some columns.

Fair enough. I think this should be good once you're ready for it. Thanks for the new feature!

**Comment by BossOfGames** [comment]
Just adding the issue link for traceability.
resolves #1681

**Pull request merged**
