### PR TITLE
Bug fix #1275

### LINKED ISSUE #1275: Make sure ranks that are in use can't be deleted and if there's 1 rank remaining it can't also be deleted

### PR DESCRIPTION
**Pull request by YashGovekar**
#1275

### CODE REVIEW

**Comment by YashGovekar** [comment]
@nabeelio Can you please look at the styleci issue. I did the required edits but still it isn't passing

**Comment by nabeelio** [comment]
Can you rebase and remove the module changes?

**Comment by YashGovekar** [comment]
> Can you rebase and remove the module changes?

Sure

**Comment by ArthurHetem** [comment]
@nabeelio, i think this can be merged, and close #1275

**Pull request merged**
