### PR TITLE
Add user switch for lang

### PR DESCRIPTION
**Pull request by arthurpar06**
This will allow each user to choose their own language, by default we will have the .env lang but it allows VAs with pilots from different countries to have the site in several languages.

### CODE REVIEW

**Comment by FatihKoz** [comment]
Do you need help for style fixes ?

**Comment by arthurpar06** [comment]
Ah yes, it didn't go well... I can try to look again tomorrow but if you want to do it, no problem.

**Comment by FatihKoz** [comment]
Hi,

I can't do it online either, but as far as I saw from the diff it should be
easy.

Tomorrow (sunday) I can check by pulling the files and then will send you
the fixed ones via discord.

Need some rest now ;)

Sent from mobile device / Mobil cihaz ile gönderildi

18 Ara 2022 Pzr 01:58 tarihinde arthurpar06 ***@***.***> şunu
yazdı:

**Comment by nabeelio** [comment]
The way i do it is there's a button to copy the diff, save it into a file and run git apply (filename of patch)  (or in intellij, you can select apply patch from keyboard)

**Comment by nabeelio** [comment]
Or sorry it's download patch and i have it open in a temporary file and copy/paste into ij

**Comment by FatihKoz** [comment]
[SytleFixedFiles.zip](https://github.com/nabeelio/phpvms/files/10253305/SytleFixedFiles.zip)

As I can not commit to the pr directly, here they are, style fixed as diff;

* App\Http\Middleware\SetActiveLanguage.php
* Config\languages.php

Hope it helps

**Comment by FatihKoz** [comment]
Also for the frontend (nav.blade.php), is it really necessary to hit App and Config facades several times? Can't we make it something like this

```php
        @php
          // Get Languages and Locale once
          $languages = Config::get('languages');
          $locale = App::getLocale();
        @endphp
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" data-boundary="viewport" aria-haspopup="true" aria-expanded="false">
            <span class="flag-icon flag-icon-{{ $languages[$locale]['flag-icon'] }}"></span>&nbsp;&nbsp;{{ $languages[$locale]['display'] }}
          </a>
          <div class="dropdown-menu dropdown-menu-right">
          @foreach ($languages as $lang => $language)
              @if ($lang != $locale)
                <a class="dropdown-item" href="{{ route('frontend.lang.switch', $lang) }}">
                  <span class="flag-icon flag-icon-{{ $language['flag-icon'] }}"></span>&nbsp;&nbsp;{{ $language['display'] }}
                </a>
              @endif
          @endforeach
          </div>
        </li>
```
At least there will be only two facade calls in blade, rest will be handled from variables/memory.

Since it is the `nav.blade.php` it will be displayed on every single page on load, can't we make those two variables somehow core provided (like they are being passed from controllers)?

**Comment by FatihKoz** [comment]
Works fine, tested on local environment (with the fixes I offered earlier today). Now it passes the checks, hope to see it live soon :)

Thanks @arthurpar06

**Comment by nabeelio** [comment]
There's just 2 things to address, looks good to me otherwise.

**Comment by FatihKoz** [comment]
Would you mind sharing those 2 things, maybe we can work on it ? Or think on it together if they are not secret of course @nabeelio

**Comment by arthurpar06** [comment]
Yes I would also be happy to help if it's not classified

**Pull request merged**
