### PR TITLE
Delete Module and Theme cache files

### LINKED ISSUE #1563: Cache not being cleaned properly (Bug Report)
When clicked `Clear all caches` button only deletes phpvms v7 cached application files from `bootstrap/cache` folder and does not delete module and theme cache.

**Version**
7.0.0-dev+230630.d76389

**To Reproduce**
1. Go to Admin > Maintenance
2. Click on `Clear all caches` button
3. Check `bootstrap\cache` folder with a file manager for timestamps
4. See the difference and not deleted old files

**Expected behavior**
All cache related files should be deleted

image

### PR DESCRIPTION
**Pull request by FatihKoz**
Delete module and theme cache files when cleaning cache from admin area as they are not being deleted by laravel anymore.

Admin > Maintenance

* Application : Clears v7 application cache **AND module cache files**
* View : Clears v7 view (blade) cache **AND theme cache files**

Closes #1563

### CODE REVIEW

**Comment by arthurpar06** [comment]
Maybe we can use the built-in artisan command for theme cache (``php artisan theme:refresh-cache``). Instead of deleting the file this function will regenerate the new one. It probably doesn't change much but it might be a little better

**Comment by FatihKoz** [comment]
If you can make it work without generating an error, why not :)

It was the first thing I tried but it causes and exception when being
called from artisan.

It works when executed from console.

In the end, it deletes the same file and the new one is created instantly,
so no difference in the result.

Sent from mobile device / Mobil cihaz ile gönderildi

9 Ara 2023 Cmt 20:46 tarihinde Arthur Parienté ***@***.***>
şunu yazdı:

**Comment by arthurpar06** [comment]
I have the same strange error. We might as well keep it that way (with the `rm`), it doesn't matter.

**Comment by FatihKoz** [comment]
Sure, either unlik() or exec('rm'...) will delete the file. End result will be same, at least we will not have cache related problems until a package based solution is provided (and not generating errors)

**Pull request merged**
