### PR TITLE
Fix Metar Decoding / Wind check for Wind Chill

### PR DESCRIPTION
**Pull request by FatihKoz**
PR aims to fix the bug #1071 by checking both the wind speed and it's value for starting Wind Chill calculation.

### CODE REVIEW

**Comment by nabeelio** [comment]
Do you have a METAR for this? I can add a test in

**Comment by FatihKoz** [comment]
We have, you can use the one from the bug report ... 

EKYT 091020Z /////KT CAVOK 02/M03 Q1019

**Comment by nabeelio** [comment]
D;oh, sorry, didn't see that

**Comment by nabeelio** [comment]
Grr, the push isn't working right

Just add this to MetarTest.php, after line 152

```php
    /**
     * https://github.com/nabeelio/phpvms/issues/1071
     */
    public function testMetarWindSpeedChill()
    {
        $metar = 'EKYT 091020Z /////KT CAVOK 02/M03 Q1019';
        $metar = Metar::parse($metar);

        $this->assertEquals('VFR', $metar['category']);
        $this->assertNull($metar['wind_speed']);
        $this->assertEquals(6.21, $metar['visibility']['mi']);
    }
```

**Comment by FatihKoz** [comment]
MetarTest update done.

**Pull request merged**
