### PR TITLE
Update SimBrief Form

### PR DESCRIPTION
**Pull request by FatihKoz**
* Added the ability to select the aircrafts assigned to the flight (via subfleets)
* Use selected aircraft (and subfleet) for random load generation according to Load Factor and Variance set for the flight (uses subfleet fares to get the capacities)
* Uses pre-defined route,alternate aerodrome and level for the flight
* Gets current UTC time, adds some margin to it (45mins - configurable via script), determines the date and passes that info to SimBrief for proper ATC FPL generation
* Gets scheduled flight time (mins) for the flight and converts it to proper format (hh mm) , passes it to SimBrief for proper Cost Index (CI) calculations
* Option for automatic SID/STAR selection (Conventional or RNAV)
* Correct flow for Plan Step Climbs applied, it is disabled by default. When enabled flight level will not be passed to SimBrief (according to SB system workflow)

* Compatible with Cargo and Passenger fleets (Cargo fleets will send the random Cargo load and 0 pax to SimBrief)
* Not Compatible with Multi Purpose Fleets (Both Cargo and Pax configured planes,think like 10tonnes of cargo and 50pax seats on a B738, they are rare but possible)

If the user leaves Fleet Fares empty and makes all capacity settings from the Flight Fares (which is not logical but possible) then random load calculation may generate unrealistic results. In the worst case 0 pax may be sent to SimBrief !

Load input is not possible at the moment 'cause manual input from the pilot will override airline/flight load factors, which will make the random load generation and load factor settings useless. Load section (and its logic) may be improved later for more flexible options.

* Uses 4 Javascript (2 for calculating times, 1 for Step Climb Dropdown, 1 for Aircraft and Subfleet Selection part)
* Uses some pure php code (mostly at aircraft configuration, capacity checking and load calculation area)

deflook

### CODE REVIEW

**Comment by nabeelio** [comment]
This is great! I might clean it up just a little bit if that's ok!

**Comment by FatihKoz** [comment]
Of course you can, this is why I created the PR.

**Comment by FatihKoz** [comment]
Commit fixes possible random Load Factor values above %100. 

This may happen if user sets non logical Load Factor (ex 95) and Variance (ex 45) values which may result a calculated random load factor above 100, this would cause a random pax/cargo generated above max capacity.

Now we will have max %100 and min %1.

**Comment by FatihKoz** [comment]
Closing this PR ... I improved the logic and the code, will post the latest edition soon. No need to have this here

**Pull request closed without merging**
