### PR TITLE
Update backups clean up config

### PR DESCRIPTION
**Pull request by arthurpar06**

### CODE REVIEW

**Comment by FatihKoz** [comment]
Considering excluded folders, should it not be good to **exclude the contents** of following folders, as they may cause problems after a restore (broken cache, server errors due to incompatible cached files etc)

* bootstrap/cache
* storage/framework/cache
* storage/framework/sessions
* storage/framework/views

We would need the folders of course (but they should be empty), in case of a restore.

Also we need to explain that the `vendor` folder is not backed up, to restore a failing site, admins would need to upload latest dev **before** unzipping the backup or run `composer install` **after** restore to get a working vendors folder.

Or we should have it in the backup, again inform people.

Just my thoughts about keeping backups efficient and easily usable.

**Comment by FatihKoz** [comment]
Test results;

* 2 VPS running on ubuntu with cyberpanel: not working
* 1 VPS running on ubuntu with plesk: not working
* 1 Shared Hosting with cPanel: not working

No errors in logs, even server php logs are clean. Probably vendor is catching exceptions and not logging errors properly.

**Comment by FatihKoz** [comment]
Possible cause for 2 vps/cyberpanel (php8.1 zip handling issues) others unknown.

Mysqldump and php zip extension is available on both servers.

**Comment by arthurpar06** [comment]
Hi,

Maybe you can try disabling the backup compression to see if it works better.
https://github.com/nabeelio/phpvms/blob/6b9658a4e37e193e00e5b1f4b1084130a64aaf1c/config/backup.php#L116-L129

If it's php-zip that's causing an error, there should be a log somewhere, perhaps in the php-cli logs (not php-fpm). Have you checked there?

**Pull request merged**
