### PR TITLE
Update DownloadController.php

### PR DESCRIPTION
**Pull request by FatihKoz**
Changed the group name according to its category , aircrafts will show icao type and registration , airports will be displayed with their icao codes names and countries. Rest will be showed with their names (exp airlines)

This will result a much better look on the downloads page for end users while looking for a specific type's files (like a repaint for a B738).

download_controller

### CODE REVIEW

**Comment by nabeelio** [comment]
Look at the Style CI details, the formatting needs to be fixed, then I'll merge.

**Comment by FatihKoz** [comment]
I really do not understand the formatting, i use tab to move on and never use spaces but it gives an error :( it really looks fine on my end

look

**Comment by nabeelio** [comment]
Click "Download Raw Diff" and then you can apply that diff using VScode (or Google how to). That'll fix the formatting.

**Comment by FatihKoz** [comment]
I think i found the problem ; the if($....) needs to be seperated like if ($....) and else ($...) , ok will close this pr and open a new one (can not use GitDesktop right now to send a commit sorry)

**Pull request closed without merging**
